model:
  type: "matcha"  # או "tacotron2" או "ringformer"
  checkpoint: "checkpoints/checkpoint_epoch=2679.ckpt"
  source: "speechbrain/tts-tacotron2-ljspeech"
  savedir: "pretrained/tacotron2"

vocoder:
  type: "hifigan"  # או "bigvgan" או "griffinlim"
  checkpoint: "checkpoints/hifigan.pt"
  source: "nvidia/bigvgan_v2_22khz_80band_fmax8k_256x"
  savedir: "pretrained/hifigan"
  sampling_rate: 22050
  denoise_strength: 0.01

inference:
  text: "שלום, מה נשמע?"
  output_path: "outputs/generated.wav"
