model:
  type: "matcha"  # או "tacotron2" או "ringformer"
  checkpoint: "/gpfs0/bgu-benshimo/users/wavishay/VallE-Heb/TTS2/Pytorch/checkpoints/matcha_tts/logs/train/ljspeech/runs/2025-06-02_14-11-39/checkpoints/checkpoint_epoch=2679.ckpt"
  source: "speechbrain/tts-tacotron2-ljspeech"
  savedir: "pretrained/tacotron2"

vocoder:
  type: "hifigan"  # או "bigvgan" או "griffinlim"
  checkpoint: "pretrained_models/hifigan_pretrained/generator.ckpt"
  source: "nvidia/bigvgan_v2_22khz_80band_fmax8k_256x"
  savedir: "pretrained/hifigan"
  sampling_rate: 22050
  denoise_strength: 0.01

inference:
  text: "שָׁלוֹם, מַה נִּשְׁמַע?"
  output_path: "outputs/generated.wav"
